# Site settings
title: "Open Source Camp @Ipotești"
email: "contact@oscamp.eu"
description: "The National Open Source Camp @Ipotești"

# About Block
aboutTitle: "About Open Source Camp"
aboutBlock:
  - title: "Conference"
    image: "conference.jpg"
    text: >
      The Open Source gathering of the year in Romania, built with care
      by geeks for enthusiasts. Awesome technical speakers and talks and
      of course, loads of fun!
  - title: "Workshops"
    image: "workshop.jpg"
    text: >
      Full-afternoons of workshops and hands-on experience, hacking and
      debugging. Join us in an epic battle to unleash the power of your
      favorite new technology!

  - title: "Capture the Flag"
    image: "capture-the-flag.jpg"
    text: >
      If your plan is to play with the latest technologies here is the
      place. Test your knowledge and skills by solving problems and
      winning lots of prizes. Knowledge in various open source fields will be
      required to pass these challenges.

  - title: "Networking"
    image: "networking.jpg"
    text: >
      OSCamp is an event specially dedicated to all those interested
      in the open source perspective. We're waiting for you at the 2nd
      edition in Botoșani, where you can meet other like minded
      open source activists.

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Floare albastră"
eventLocationLink: "http://www.cautpensiuni.ro/pensiune/pensiunea-floare-albastra-ipotesti-botosani"
eventStreetAddress: "Ipotești"
eventAddressLocality: "Botoșani"
eventAddressLocalityRegion: "Botoșani"
eventPostalCode: "700506"
eventAddressCountry: "Romania"
eventStartTime: "2017-08-07T12:00"
eventDoorTime: "08:00"
eventEndTime: "2017-08-12T12:00"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "ipotesti_2017_2.jpg"
venueSmallImage1: "ipotesti_2017_0.jpg"
venueSmallImage2: "ipotesti_2017_1.jpg"
venueSmallImage3: "ipotesti_2017_3.jpg"
venueTitle: "Floarea albastră, Ipotești, Botoșani"
venueFeatures:
  - "- open air theatre"
  - "- 6 bungalows (with 4 rooms)"
  - "- 1 VIP bungalow (with 3 rooms)"
  - "- 4 VIP rooms"

# Team Block
teamBlockTitle: "About us"
aboutUs: >
    Finally, the step we've been waiting for has been taken by a large
    amount of tech industry giants and important figures. From the beginning
    of the IT industry, the Open Source trend has been an element of geek legends,
    but the myth becomes reality in a push of the industry towards greater grounds.
    In our enthusiasm, we want to share the beautiful things this old taboo subject has
    to offer in the software industry, with the help, of course, of great minds with
    state of the art skills. So we hope you'll give us the chance to impress in our
    Open Source Camp hosted in Ipotești, Romania this year. Join us for tech talks,
    workshops and an awesome CTF that will keep you up in excitement with a
    variety of specially crafted challenges and prizes.

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - count: "65"
   specialCharacter: "&middot;"
   info: "attendees"
   detail: "from everywhere"

 - count: "5"
   specialCharacter: "&middot;"
   info: "days"
   detail: "of pure open source technologies"

 - count: "20"
   specialCharacter: "&middot;"
   info: "speakers"
   detail: "from country and beyond"

# Rockstar Speakers Block
rockstar:
    title: "Meet our awesome speakers"
    background: "rockstar-speakers.jpg"
    speakers_count: 4
    speakers_url: "/speakers/"

# Documents
c4pUrl: null

footerBlocks:
 - title: "Contact"
   links:
      - {link: "mailto:contact@oscamp.eu", text: "contact@oscamp.eu"}

 - title: "FAQ"
   links:
      - {permalink: "/cod/", text: "Code of Conduct"}

 - title: "Previous edition"
   links:
      - {permalink: "/2016/", text: "OSCamp 2016"}
